### ISSUE TITLE
Debug observations break Hidden Agenda

### ISSUE THREAD

**Issue by olipinski** [google-deepmind/meltingpot#168]
After setting the `_ENABLE_DEBUG_OBSERVATIONS = True` for Hidden Agenda, the environment breaks.

https://github.com/deepmind/meltingpot/blob/dfff4d2784ebab1f9caba299b4099c6092f9fd70/meltingpot/configs/substrates/hidden_agenda.py#L67

The error is as below:

```
Traceback (most recent call last):
  File "/home/user1/anaconda3/envs/hidden_agenda_test/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/user1/anaconda3/envs/hidden_agenda_test/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/mnt/c/Users/oll1u20/repos/hidden_agenda_test/hidden_agenda_test/evaluate.py", line 263, in main
    test_env = mp_wrapper.env_creator(env_config)
  File "/mnt/c/Users/oll1u20/repos/hidden_agenda_test/hidden_agenda_test/utils/mp_wrapper.py", line 512, in env_creator
    env = MeltingPotEnv(config)
  File "/mnt/c/Users/oll1u20/repos/hidden_agenda_test/hidden_agenda_test/utils/mp_wrapper.py", line 119, in __init__
python-BaseException
    env = substrate.build_from_config(
  File "/home/user1/anaconda3/envs/hidden_agenda_test/lib/python3.10/site-packages/meltingpot/substrate.py", line 60, in build_from_config
    return get_factory_from_config(config).build(roles)
  File "/home/user1/anaconda3/envs/hidden_agenda_test/lib/python3.10/site-packages/meltingpot/utils/substrates/substrate_factory.py", line 91, in build
    return substrate.build_substrate(
  File "/home/user1/anaconda3/envs/hidden_agenda_test/lib/python3.10/site-packages/meltingpot/utils/substrates/substrate.py", line 129, in build_substrate
    env = builder.builder(lab2d_settings)
  File "/home/user1/anaconda3/envs/hidden_agenda_test/lib/python3.10/site-packages/meltingpot/utils/substrates/builder.py", line 190, in builder
    env = reset_wrapper.ResetWrapper(build_environment)
  File "/home/user1/anaconda3/envs/hidden_agenda_test/lib/python3.10/site-packages/meltingpot/utils/substrates/wrappers/reset_wrapper.py", line 32, in __init__
    env = build_environment()
  File "/home/user1/anaconda3/envs/hidden_agenda_test/lib/python3.10/site-packages/meltingpot/utils/substrates/builder.py", line 182, in build_environment
    env_raw = dmlab2d.Lab2d(_DMLAB2D_ROOT, lab2d_settings_dict)
ValueError: 
ERROR: ....10/site-packages/meltingpot/lua/modules/game_object.lua:472: Component does not exist: Avatar
stack trace-back:
ERROR: [C]: in function 'assert'
ERROR: @/home/user1/anaconda3/envs/hidden_agenda_test/lib/python3.10/site-packages/meltingpot/lua/modules/game_object.lua:472: in function 'getComponent'
ERROR: @/home/user1/anaconda3/envs/hidden_agenda_test/lib/python3.10/site-packages/meltingpot/lua/modules/component_library.lua:828: in function 'addObservations'
ERROR: @/home/user1/anaconda3/envs/hidden_agenda_test/lib/python3.10/site-packages/meltingpot/lua/modules/game_object.lua:395: in function 'func'
ERROR: @/home/user1/anaconda3/envs/hidden_agenda_test/lib/python3.10/site-packages/meltingpot/lua/modules/game_object.lua:160: in function '_doOnAllComponents'
ERROR: @/home/user1/anaconda3/envs/hidden_agenda_test/lib/python3.10/site-packages/meltingpot/lua/modules/game_object.lua:392: in function 'addObservations'
ERROR: @/home/user1/anaconda3/envs/hidden_agenda_test/lib/python3.10/site-packages/meltingpot/lua/modules/base_simulation.lua:366: in function 'addObservations'
ERROR: @/home/user1/anaconda3/envs/hidden_agenda_test/lib/python3.10/site-packages/meltingpot/lua/modules/api_factory.lua:66:
```

**Comment by duenez** [comment]
I'll take a look later this week.

**Comment by olipinski** [comment]
Hi @duenez, any luck with this issue?
