### ISSUE TITLE
Can't run examples/pettingzoo/sb3_train.py

### ISSUE THREAD

**Issue by ZzzihaoGuo** [google-deepmind/meltingpot#269]
Hi,
I installed the environment according to the examples/requirements.txt, but an error occurred.
`stable_baselines3            2.3.2
SuperSuit                    3.7.2
PettingZoo                   1.22.3
`

Traceback (most recent call last):
  File "/root/autodl-tmp/Benchmarking-Meltingpot/examples/pettingzoo/sb3_train.py", line 29, in <module>
    import supersuit as ss
  File "/root/miniconda3/envs/mp/lib/python3.10/site-packages/supersuit/__init__.py", line 1, in <module>
    from supersuit.generic_wrappers import clip_actions_v0  # NOQA
  File "/root/miniconda3/envs/mp/lib/python3.10/site-packages/supersuit/generic_wrappers/__init__.py", line 12, in <module>
    from .delay_observations import delay_observations_v0  # NOQA
  File "/root/miniconda3/envs/mp/lib/python3.10/site-packages/supersuit/generic_wrappers/delay_observations.py", line 4, in <module>
    from .utils.shared_wrapper_util import shared_wrapper
  File "/root/miniconda3/envs/mp/lib/python3.10/site-packages/supersuit/generic_wrappers/utils/shared_wrapper_util.py", line 4, in <module>
    from pettingzoo.utils import BaseParallelWrapper
ImportError: cannot import name 'BaseParallelWrapper' from 'pettingzoo.utils' (/root/miniconda3/envs/mp/lib/python3.10/site-packages/pettingzoo/utils/__init__.py)

I can solve the problem by installing lower versions of SuperSuit, stable_baselines3, and PettingZoo.
`PettingZoo==1.14.0
stable_baselines3==2.4.0a7
SuperSuit==3.3.2
`
But When I run the code, It seems that multi-core CPUs and multiple environments have little effect. 12 CPUs and 12 envs almost have the same performance with 1 CPU and 1 env.
Could you please provide more complete requirements.txt?

By the way, I am trying to use sbx(sb3 + jax) to make the pettingzoo framework to be faster, I don't know whether you would do the similar work. Thank you so much.

**Comment by marimeireles** [comment]
As of today this is breaking in different ways.
I was also able to solve this issue by installing Python 3.11, gymnasium 1.0.0, pettingzoo 1.24.3, supersuit 3.9.3 and stable_baselines3 2.4.1.
However, I got some problems with the imports which I fixed with:
```
diff --git a/examples/pettingzoo/utils.py b/examples/pettingzoo/utils.py
index d54923d..6963112 100644
--- a/examples/pettingzoo/utils.py
+++ b/examples/pettingzoo/utils.py
@@ -22,7 +22,7 @@ from ml_collections import config_dict
 from pettingzoo import utils as pettingzoo_utils
 from pettingzoo.utils import wrappers

-from ..gym import utils
+from examples.gym import utils
```
And then running the file with `python -m examples.pettingzoo.sb3_train`
But I guess I'm now falling into some traps because one(some?) of the packages I've installed are wrong, e.g. `TypeError: unhashable type: 'ConfigDict'`.

**Comment by marimeireles** [comment]
Even as I use the same libraries as the user above I'm not able to run the examples due to:

```
  File "dev/meltingpot/meltingpot/configs/substrates/__init__.py", line 60, in get_config
    if substrate not in SUBSTRATES:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unhashable type: 'ConfigDict'
```

**Comment by jzleibo** [comment]
Do we know of anyone who ever successfully used pettingzoo? We've never tried it or tested it ourselves. My inclination would simply be to remove support for it, and maybe for all the training examples. It's not clear what value they add, we've never used them.

**Comment by jzleibo** [comment]
Sounds like a much better idea to stick to the vanilla MeltingPot + your own implementation of PPO. 

It was probably a bad idea on our part in the first place to have included the training examples. They seem to be more trouble than they are worth, given that we don't use them ourselves (we have our own RL code internally). 

For PettingZoo in particular, I have no idea if the PettingZoo example ever really worked. I only looked at it once when it was first added, and was very skeptical at that time that it could work well, since it looked to me like the only RL library it was connected to on the other side was one that did not support recurrent networks (no idea if this is still true or not). And no one ever showed me an example training curve produced with PettingZoo... So I never got any evidence that it was working in all this time. That, combined with the fact that it's apparently broken now, seems like a good enough reason to delete it I think.

**Comment by marimeireles** [comment]
Aha well, that's helpful!
Thank you @jzleibo. Let me know, I'm happy to remove them and update the requirements files/installation instructions for them.

**Comment by jzleibo** [comment]
thanks @marimeireles, it's probably easiest if we delete it on our end. Thank you for bringing this to our attention!
